apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connector-configuration-role
  namespace: debezium
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["demodebezium-secrets"]
  verbs: ["get"]

